-- MySQL Script generated by MySQL Workbench
-- 11/22/16 16:32:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dsoutlet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dsoutlet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dsoutlet` DEFAULT CHARACTER SET utf8 ;
USE `dsoutlet` ;

-- -----------------------------------------------------
-- Table `dsoutlet`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Usuario` (
  `IDUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Acesso` ENUM('A', 'C') NOT NULL,
  PRIMARY KEY (`IDUsuario`));


-- -----------------------------------------------------
-- Table `dsoutlet`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Produto` (
  `IDProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Tamanho` VARCHAR(45) NOT NULL,
  `Quantidade` INT NOT NULL,
  `PrecoEntrada` DECIMAL(5,2) NULL,
  `PrecoSaidaPadrao` DECIMAL(5,2) NULL,
  PRIMARY KEY (`IDProduto`));


-- -----------------------------------------------------
-- Table `dsoutlet`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Endereco` (
  `IDEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cep` VARCHAR(9) NOT NULL,
  `Logradouro` VARCHAR(80) NOT NULL,
  `Numero` INT NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDEndereco`, `Cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dsoutlet`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Loja` (
  `IDLoja` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `EnderecoIDEndereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDLoja`, `EnderecoIDEndereco`),
  INDEX `fk_Loja_Endereco1_idx` (`EnderecoIDEndereco` ASC),
  CONSTRAINT `fk_Loja_Endereco1`
    FOREIGN KEY (`EnderecoIDEndereco`)
    REFERENCES `dsoutlet`.`Endereco` (`IDEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dsoutlet`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Cliente` (
  `IDCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `Email` VARCHAR(50) NULL,
  `Divida` DECIMAL(5,2) NULL,
  `ParcelasAPagar` INT NULL,
  `Vencimento` DATE NULL,
  `EnderecoIDEndereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDCliente`, `CPF`, `EnderecoIDEndereco`),
  INDEX `fk_Cliente_Endereco1_idx` (`EnderecoIDEndereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`EnderecoIDEndereco`)
    REFERENCES `dsoutlet`.`Endereco` (`IDEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dsoutlet`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`Venda` (
  `IDVenda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Valor` DECIMAL(5,2) NOT NULL,
  `TipoDePagamento` VARCHAR(45) NOT NULL,
  `Tempo` TIMESTAMP NOT NULL,
  `ClienteCPF` VARCHAR(45) NULL,
  `UsuarioIDUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDVenda`, `UsuarioIDUsuario`),
  INDEX `fk_Venda_Cliente1_idx` (`ClienteCPF` ASC),
  INDEX `fk_Venda_Usuario1_idx` (`UsuarioIDUsuario` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`ClienteCPF`)
    REFERENCES `dsoutlet`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`UsuarioIDUsuario`)
    REFERENCES `dsoutlet`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dsoutlet`.`RegistroEntrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`RegistroEntrada` (
  `IDRegistro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NOT NULL,
  `Tempo` TIMESTAMP NOT NULL,
  `LojaIDLoja` INT UNSIGNED NOT NULL,
  `ProdutoIDProduto` INT UNSIGNED NOT NULL,
  `UsuarioIDUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDRegistro`, `UsuarioIDUsuario`),
  INDEX `fk_Registro_Entrada_Loja1_idx` (`LojaIDLoja` ASC),
  INDEX `fk_Registro_Entrada_Produto1_idx` (`ProdutoIDProduto` ASC),
  INDEX `fk_Registro_Entrada_Usuario1_idx` (`UsuarioIDUsuario` ASC),
  CONSTRAINT `fk_Registro_Entrada_Loja1`
    FOREIGN KEY (`LojaIDLoja`)
    REFERENCES `dsoutlet`.`Loja` (`IDLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Entrada_Produto1`
    FOREIGN KEY (`ProdutoIDProduto`)
    REFERENCES `dsoutlet`.`Produto` (`IDProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Entrada_Usuario1`
    FOREIGN KEY (`UsuarioIDUsuario`)
    REFERENCES `dsoutlet`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dsoutlet`.`RegistroSaida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`RegistroSaida` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tempo` TIMESTAMP NOT NULL,
  `LojaIDLoja` INT UNSIGNED NOT NULL,
  `VendaIDVenda` INT UNSIGNED NOT NULL,
  `UsuarioIDUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`, `UsuarioIDUsuario`),
  INDEX `fk_Registro_Saida_Loja1_idx` (`LojaIDLoja` ASC),
  INDEX `fk_Registro_Saida_Venda1_idx` (`VendaIDVenda` ASC),
  INDEX `fk_Registro_Saida_Usuario1_idx` (`UsuarioIDUsuario` ASC),
  CONSTRAINT `fk_Registro_Saida_Loja1`
    FOREIGN KEY (`LojaIDLoja`)
    REFERENCES `dsoutlet`.`Loja` (`IDLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Saida_Venda1`
    FOREIGN KEY (`VendaIDVenda`)
    REFERENCES `dsoutlet`.`Venda` (`IDVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Saida_Usuario1`
    FOREIGN KEY (`UsuarioIDUsuario`)
    REFERENCES `dsoutlet`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dsoutlet`.`LinhaDeVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsoutlet`.`LinhaDeVenda` (
  `VendaIDVenda` INT UNSIGNED NOT NULL,
  `ProdutoIDProduto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`VendaIDVenda`, `ProdutoIDProduto`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`ProdutoIDProduto` ASC),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`VendaIDVenda` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`VendaIDVenda`)
    REFERENCES `dsoutlet`.`Venda` (`IDVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`ProdutoIDProduto`)
    REFERENCES `dsoutlet`.`Produto` (`IDProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
